version: "3.9"
services:
  fhi_mission_stack_devel:
    image: fhi-git.fraunhofer.it:5050/rise-libs/ro/mi/fhi_mission_stack:devel
    build:
      context: ..
      dockerfile: docker/devel.dockerfile
    tty: true
    environment:
      #- ROS_MASTER_URI=http://localhost:11311
      #- ROS_HOSTNAME=localhost
      - PYTHONUNBUFFERED=1
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    network_mode: host
    privileged: true
    volumes:
      - ./..:/mission_stack_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
    command:
      terminator