version: "3.9"
services:
  fhi_mission_stack_release:
    image: fhi-git.fraunhofer.it:5050/rise-libs/ro/mi/fhi_mission_stack:release
    build:
      context: ..
      dockerfile: docker/release.dockerfile
      args:
        - "DOCKER_BUILDKIT: 1"
    tty: true
    environment:
      #- ROS_MASTER_URI=http://localhost:11311
      #- ROS_HOSTNAME=localhost
      - PYTHONUNBUFFERED=1
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    network_mode: host
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
    command:
      terminator