bt_executor_node:
  ros__parameters:
    is_terminal_logging: true
    is_logging: true
    log_folder_name: "logs/"
    loop_rate: 10
    zmq_publisher_port: 1666
    zmq_server_port: 1667
    behavior_tree_definitions_path: "config/trees/behavior_trees.yaml"
    behavior_trees_path: "config/trees"
    default_tree_name: "test_tree"
