version: "3.9"
services:
  behavior_tree_stack_devel:
    image: fhi-git.fraunhofer.it:5050/behavior-tree/behavior_tree_stack:devel
    container_name: bt_stack
    build:
      context: ..
      dockerfile: docker/devel.dockerfile
    tty: true
    environment:
      - PYTHONUNBUFFERED=1
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    network_mode: host
    privileged: true
    volumes:
      - ./..:/behavior_tree_stack_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw