version: "3.9"
services:
  concert_mission:
    image: concert_mission
    container_name: concert_mission
    build:
      context: ..
      dockerfile: docker/Dockerfile
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_NETWORK_INTERFACE=${ROS_NETWORK_INTERFACE}
      - CYCLONEDDS_URI=${CYCLONEDDS_URI}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    network_mode: host
    privileged: true
    volumes:
      - ../:/concert_mission_ws/
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw